const userRatings = [
  {
    id: 1,
    name: "shivansh gupta",
    email: "shivansh11g@gmail.com",
    ratings: 4,
    comment: "Pleasant Experience",
    feedback: "rvrbjb",
  },
  {
    id: 2,
    name: "Akash gupta",
    email: "akash11g@gmail.com",
    ratings: 2,
    comments: "Pleasant Experience and very good feel",
    feedback: "rvrbjb",
  },
  {
    id: 3,
    name: "Aman gupta",
    email: "aman11g@gmail.com",
    rating: 5,
    comments: "very bad feel",
    feedback: "rvrbjb",
  },
  {
    id: 4,
    name: "Ankit gupta",
    email: "ankit11g@gmail.com",
    rating: 5,
    comments: " good feel",
    feedback: "rvrbjb",
  },
  {
    id: 5,
    name: "Priya gupta",
    email: "priya11g@gmail.com",
    rating: 1,
    comments: "very legitimate feel",
    feedback: "rvrbjb",
  },
  {
    id: 6,
    name: "Shiva Singh",
    email: "shiva11g@gmail.com",
    rating: 2,
    comments: "very good ",
    feedback: "rvrbjb",
  },
  {
    id: 7,
    name: "Shubhi Srivastava",
    email: "shubhi11g@gmail.com",
    rating: 3,
    comments: " feel",
    feedback: "rvrbjb",
  },
  {
    id: 8,
    name: "Vaibhav Singh",
    email: "Vaibhav11g@gmail.com",
    rating: 4,
    comments: " good feel",
    feedback: "rvrbjb",
  },
  {
    id: 9,
    name: "Shyam dwivedi",
    email: "shyam11g@gmail.com",
    rating: 5,
    comments: "very good feel",
    feedback: "rvrjnbjb",
  },
  {
    id: 10,
    name: "Shyam varan",
    email: "Shyam11g@gmail.com",
    rating: 1,
    comments: "very bad feel",
    feedback: "rvrbjbg",
  },
  {
    id: 11,
    name: "shivansh gupta",
    email: "shivansh11g@gmail.com",
    ratings: 4,
    comment: "Pleasant Experience",
    feedback: "rvrbjb",
  },
  {
    id: 12,
    name: "Akash gupta",
    email: "akash11g@gmail.com",
    ratings: 2,
    comments: "Pleasant Experience and very good feel",
    feedback: "rvrbjb",
  },
  {
    id: 13,
    name: "Aman gupta",
    email: "aman11g@gmail.com",
    rating: 5,
    comments: "very bad feel",
    feedback: "rvrbjb",
  },
  {
    id: 14,
    name: "Ankit gupta",
    email: "ankit11g@gmail.com",
    rating: 5,
    comments: " good feel",
    feedback: "rvrbjb",
  },
  {
    id: 15,
    name: "Priya gupta",
    email: "priya11g@gmail.com",
    rating: 1,
    comments: "very legitimate feel",
    feedback: "rvrbjb",
  },
  {
    id: 16,
    name: "Shiva Singh",
    email: "shiva11g@gmail.com",
    rating: 2,
    comments: "very good ",
    feedback: "rvrbjb",
  },
  {
    id: 17,
    name: "Shubhi Srivastava",
    email: "shubhi11g@gmail.com",
    rating: 3,
    comments: " feel",
    feedback: "rvrbjb",
  },
  {
    id: 18,
    name: "Vaibhav Singh",
    email: "Vaibhav11g@gmail.com",
    rating: 4,
    comments: " good feel",
    feedback: "rvrbjb",
  },
  {
    id: 19,
    name: "Shyam dwivedi",
    email: "shyam11g@gmail.com",
    rating: 5,
    comments: "very good feel",
    feedback: "rvrjnbjb",
  },
  {
    id: 20,
    name: "Shyam varan",
    email: "Shyam11g@gmail.com",
    rating: 1,
    comments: "very bad feel",
    feedback: "rvrbjbg",
  },
];

module.exports = userRatings;
